#!/usr/bin/env bash
#allows nginx on the firewall

#sudo ufw allow 'NGINX HTTPS'
#change ownership to current user
#sudo chown -R "$USER:$USER" /var/www/html
#sudo chmod -R 755 /var/www/
nginx_conf="/etc/nginx/sites-enabled/default"

# Define the redirection rule
redirect_path="/redirect_me/"
uri="https://www.youtube.com/watch?v=QH2-TGUlwu4"

sudo sed -i "48i \ \ \ \ location $redirect_path {\n \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ return 301 $uri;\n \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ }" $nginx_conf

#backup the default nginx page
#cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debain.bak

sudo service nginx restart
