#!/usr/bin/env bash
# Define the path to the Nginx configuration file

nginx_conf="/etc/nginx/sites-enabled/default"
nginx_root="/var/www/html"
custom_error_page="/var/www/html/404.html"
output_string="Ceci n'est pas une page"


# Check if the custom error page exists
if [ ! -f "$custom_error_page" ]; then
  # Custom error page HTML file with the desired message
  echo -e "Ceci n'est pas une page \n" > /var/www/html/404.html
fi

# Add the error_page directive within the server block
sudo sed -i '/^server {/a \\n\    error_page 404 \/404.html;' "$nginx_conf"


# If the configuration test is successful, reload Nginx to apply the changes
service nginx restart
