#!/usr/bin/env bash
# Define the path to the Nginx configuration file

nginx_conf="/etc/nginx/sites-enabled/default"
custom_error_page="/var/www/html/404.html"

# Update the server.
sudo apt-get update

# Install Nginx and agree to all prompts.
sudo apt-get -y install nginx

# start nginx
sudo service nginx start


#change ownership to current user
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/

# Check if the custom error page exists
if [ ! -f "$custom_error_page" ]; then
  # Custom error page HTML file with the desired message
  echo -e "Ceci n'est pas une page \n" > /var/www/html/404.html
fi

# Add the error_page directive within the server block
sudo sed -i '/^server {/a \\n\    error_page 404 \/404.html;' "$nginx_conf"

sudo nginx -t

# If the configuration test is successful, reload Nginx to apply the changes
sudo service nginx restart
