#!/usr/bin/env bash
# install nginx on web-01

nginx_conf="/etc/nginx/sites-enabled/default"


sudo apt update
sudo apt-get -y install nginx
sudo sed -i 's/80/80/g' /etc/nginx/sites-enabled/default

sudo chmod -R 755 /var/www
sudo chown -R $USER:$USER /var/www/html
echo "Hello World!" > /var/www/html/index.html


# Define the redirection rule
redirect_path="/redirect_me/"
uri="https://www.github.com/MOSES-do"
sudo sed -i "48i \ \ \ \ location $redirect_path {\n \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ return 301 $uri;\n \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ }" $nginx_conf


# Custom error page HTML file with the desired message
echo -e "Ceci n'est pas une page \n" > /var/www/html/404.html
# Add the error_page directive within the server block
sudo sed -i '/^server {/a \\n\    error_page 404 \/404.html;' "$nginx_conf"


#Add custom header to config using sed inplace
sudo sed -i "/server_name _;/a add_header X-Served-By "$HOSTNAME";" /etc/nginx/sites-enabled/default


#Test configuration fo possible errors
sudo nginx -t

#Restart nginx
sudo service nginx restart
