#!/usr/bin/env bash
# Define the path to the Nginx configuration file
nginx_conf="/etc/nginx/sites-available/default"

# install nginx on web-01
sudo apt update
sudo apt-get -y install nginx
sudo sed -i 's/80/80/g' "$nginx_conf"

#start nginx
sudo service nginx start

#change ownership to current user
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/
echo "Hello World!" > /var/www/html/index.html

#add custom header to config
sudo sed -i '/server_name _;/a\\tadd_header X-Served-By $HOSTNAME;' "$nginx_conf"


# Define the redirection rule
redirect_path="/redirect_me/"
uri="https://www.youtube.com/watch?v=QH2-TGUlwu4"
sudo sed -i "48i \ \ \ \ \tlocation $redirect_path {\n \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ return 301 $uri;\n \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ }" $nginx_conf


# Add the error_page directive within the server block
sudo sed -i '0,/try_files $uri $uri\/ =404;/s//&\n\t\terror_page 404 \/404.html;/' "$nginx_conf"

# Delete existing file and create a symlink using updated sites-available/default file
#sudo rm -r "/etc/nginx/sites-enabled/default"

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo nginx -t
#backup the default nginx page
#cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debain.bak

# If the configuration test is successful, reload Nginx to apply the changes
sudo service nginx restart
