#!/usr/bin/env bash
# Install & config HAproxy on lb-01 server to send traffic to web-01 and web-02.

# Update the server.
sudo apt-get update

# Install Nginx and agree to all prompts.
sudo apt-get -y install haproxy

# Create addition for haproxy.cfg file
addition=\
"
frontend external_end
  bind *:80
        mode http
        default_backend server_end

backend server_end
  balance roundrobin
	option http-server-close
        server 530721-web-01 100.25.143.79 check
  server 530721-web-02 100.25.222.39 check
"

# First, assign ownership of haproxy to user running script
# so they have full control over web server files.
sudo chown -R "$USER:$USER" /etc/haproxy

# Second, set permissions of /etc/haproxy & its files to rwx for user,
# r-x for group and others.
sudo chmod -R 755 /etc/haproxy

# Append addition to haproxy.cfg
echo "$addition" | sudo tee -a /etc/haproxy/haproxy.cfg

# First, assign ownership of default to user running script
# so they have full control over web server files.
sudo chown -R "$USER:$USER" /etc/default

# Second, set permissions of /var/www & its files to rwx for user,
# r-x for group and others.
sudo chmod -R 755 /etc/default

# Make haproxy startable automatically with init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Test configuration
haproxy -c -f /etc/haproxy/haproxy.cfg


# Restart haproxy
sudo service haproxy restart
