#!/usr/bin/env bash
# bash script that generates a MySQL dump and creates a compressed archive out of it

if [ $# -ne 1 ]; then
	echo "USAGE: $0 <password>"
	exit 1
fi

dump_file="backup.sql"

timestamp=$(date +"%d-%m-%Y")
archive_file="$timestamp.tar.gz"
sudo mysqldump -u root -p$1 --all-databases > $dump_file
if [ $? -ne 0 ]; then
	echo "my sql dump failed"
	exit 1
fi
tar -cvzf "$archive_file" "$dump_file"

if [ $? -ne 0 ]; then
	echo "Error: failed to create compressed archive"
	exit 1
fi
