#!/usr/bin/env bash
#print a clock time for 12hrs and 59min
h="0"
while [ "$h" -le 12 ]
do
    m="1"
    echo "Hour: $h"
    while [ "$m" -le 59 ]
    do
        echo "$m"
    ((m++))
    done
((h++))
done

